import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { LanguageProvider } from "@/context/LanguageContext";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { SoundListener } from "@/components/SoundListener";
import "./globals.css";

const lilitaOne = localFont({
  src: "../public/fonts/LilitaOne-Regular.ttf",
  variable: "--font-lilita-one",
  display: "swap",
  preload: true,
  fallback: ["cursive"],
});

/* ─── SEO Target Keywords ─── */
const seoKeywords = [
  "rizz",
  "rizz ai",
  "rizz app",
  "dating ai",
  "ai dating app",
  "rizz gpt",
  "ai rizz",
  "rizz app online",
  "rizz app free",
  "ai dating chatbot",
  "rizzai.space",
  "rizz space",
  "rizzai",
  "RIZZ AI chat",
  "Free Rizz AI",
  "RizzChat app",
  "Rizz AI response",
  "RIZZ AI bot",
  "Free Rizz AI website",
  "Rizz ai gemini",
  "Dating assistant AI free",
  "Smooth Rizz AI",
  "Rizz AI free online",
  "Free rizz ai download",
  "Free rizz ai apk",
  "Free rizz ai for android",
  "Best free rizz ai",
  "RIZZ AI assistant",
  "Rizz ai assistant app",
  "Rizz AI free",
  "Rizz ai assistant review",
  "Rizz AI dating assistant",
  "Plug AI Rizz app",
  "Rizz AI screenshot",
  "pick up lines",
  "rizz lines",
  "flirting pick up lines",
  "best pick up lines",
  "funny pick up lines",
  "cheesy pick up lines",
  "good pick up lines",
  "best rizz lines",
  "corny pick up lines",
  "rizz pick up lines",
  "rizz pickup lines",
  "pick up lines for guys",
  "cute pick up lines",
  "good rizz lines",
  "rizz up lines",
  "smooth rizz lines",
  "pick up lines funny",
  "pick up lines with rizz",
  "free rizz app",
  "free ai wingman",
  "ai wingman app",
  "free dating assistant",
  "free dating assistant app",
  "couple goals",
  "couples goals",
  "couple goals questions",
  "hot or not",
  "rizzapp",
  "rizzing",
  "rizz apps free",
  "rizz generator",
  "rizz reply app",
  "rizzbot",
  "rizz helper",
  "looksmaxing rating",
  "looksmax",
  "looksmaxing ai",
  "looksmaxing meaning",
  "look max",
  "how to looksmax",
  "looksmaxing scale app",
  "looksmaxing scale",
  "how to glow up",
  "glow up tips",
  "looksmax ai",
  "face rating",
  "face attractiveness test",
  "attractiveness face test",
  "looksmaxxed",
  "looksmaxing",
  "looksmaxxing",
  "looksmaxing app",
  "psl scale",
  "ai face rater",
  "psl rating test",
  "psl rating scale",
  "tinder",
  "hinge",
  "bumble",
  "couple games",
  "couples games",
  "game of questions for couples",
  "hot or not website",
  "roast my selfie",
  "rate my crush",
  "love test name",
  "love calculator names",
  // German & Slang SEO Keywords
  "Ausstrahlung",
  "Strahl",
  "Läuft bei dir",
  "Klarkommen",
  "Flirten",
  "Mein Crush",
  "Digga / Alter",
  "Digga",
  "Alter",
  "Geil / Krass",
  "Geil",
  "Krass",
  "Ghosten",
  "Simpen",
  "Anmachsprüche",
  "Flirt Tastatur",
  "KI Dating / KI Chat",
  "KI Dating",
  "KI Chat",
  "Phrase d'accroche Tinder",
  "Assistant de drague IA",
  "Comment avoir du rizz",
  "Générateur de répliques",
  "KI-Rizz",
  "KI-Flirt-Assistent",
  "KI-Dating-Assistent",
  "KI-Sexy-Assistent",
  "KI-Verführungsassistent",
  "Rizz-App",
  "Rizz KI",
  "Rizz Generator",
  "Rizz-Generator",
  "Rizz auf Deutsch",
  "Deutscher Rizz",
  "Rizz Sprüche",
  "Rizz Sprüche Generator",
  "Rizz Lines",
  "Rizz Lines auf Deutsch",
  "Rizzler",
  "Rizz haben",
  "mehr Rizz haben",
  "Wie bekomme ich Rizz",
  "Flirt-Sprüche",
  "Flirtsprüche",
  "Flirtsprüche Generator",
  "Anmachsprüche Generator",
  "beste Anmachsprüche",
  "lustige Anmachsprüche",
  "süße Anmachsprüche",
  "freche Anmachsprüche",
  "romantische Anmachsprüche",
  "Anmachsprüche für Frauen",
  "Anmachsprüche für Männer",
  "Anmachsprüche Tinder",
  "Tinder Sprüche",
  "Tinder Anmachsprüche",
  "Tinder Opener",
  "Tinder Eröffnungsspruch",
  "erste Nachricht Tinder",
  "erste Nachricht nach Match",
  "was schreiben nach Match",
  "was soll ich meinem Match schreiben",
  "Tinder Nachricht schreiben",
  "Tinder Chat Tipps",
  "Tinder Flirtsprüche",
  "Bumble Anmachsprüche",
  "Bumble erste Nachricht",
  "Bumble Opener",
  "Hinge Opener",
  "Dating-Sprüche",
  "Dating-Tipps",
  "Flirt-Tipps",
  "Flirt-Tipps für Männer",
  "Flirt-Tipps für Frauen",
  "Flirten lernen",
  "richtig flirten",
  "online flirten",
  "beim Chatten flirten",
  "jemanden anschreiben",
  "Mädchen anschreiben",
  "Frau anschreiben",
  "Jungen anschreiben",
  "Mann anschreiben",
  "Crush anschreiben",
  "was soll ich schreiben",
  "was soll ich ihr schreiben",
  "was soll ich ihm schreiben",
  "was antworten auf Nachricht",
  "was soll ich darauf antworten",
  "was antworten beim Flirten",
  "Flirt-Antworten",
  "freche Antworten",
  "lustige Antworten",
  "schlagfertige Antworten",
  "Flirt-Antwort Generator",
  "KI Antwort Generator",
  "KI Chat Antwort",
  "KI für Dating",
  "KI zum Flirten",
  "KI für Tinder",
  "KI Tinder Assistent",
  "Tinder KI",
  "Dating KI",
  "Flirt KI",
  "KI Flirt Generator",
  "KI Anmachspruch Generator",
  "KI Flirtspruch Generator",
  "KI Nachrichten Generator",
  "KI Chat Generator",
  "KI Dating Coach",
  "KI Flirt Coach",
  "Dating Coach KI",
  "Flirt Coach KI",
  "Verführungstipps",
  "Verführungskunst",
  "Flirt-Coach",
  "Flirt-App",
  "Dating-App",
  "Flirt-App KI",
  "Chat-Flirt KI",
  "Chat-Assistent Dating",
  "Icebreaker",
  "Icebreaker Sprüche",
  "Icebreaker für Tinder",
  "Gespräch anfangen",
  "Gespräch beginnen",
  "Gespräch am Laufen halten",
  "Gesprächsthemen Dating",
  "Gesprächsthemen Tinder",
  "Gespräch mit Crush anfangen",
  "jemanden zum Lachen bringen",
  "Komplimente",
  "Flirt-Komplimente",
  "Komplimente für Frauen",
  "Komplimente für Männer",
  "süße Nachrichten",
  "flirty Nachrichten",
  "flirty Sprüche",
  "sexy Sprüche",
  "romantische Nachrichten",
  "romantische Sprüche",
  "Disse zum Flirten",
  "Pickup Lines Deutsch",
  "Pickup Lines auf Deutsch",
  "Pickup Line Generator Deutsch",
  // French SEO Keywords
  "phrase de drague",
  "phrases de drague",
  "phrase d'accroche",
  "phrase d’accroche",
  "phrases d'accroche",
  "phrases d’accroche",
  "phrase d'accroche Tinder",
  "phrase d’accroche Tinder",
  "premier message Tinder",
  "phrase Tinder",
  "phrase de drague Tinder",
  "message Tinder",
  "phrase pour draguer",
  "phrases pour draguer",
  "phrase pour aborder",
  "phrase pour briser la glace",
  "message pour un match Tinder",
  "assistant de drague IA",
  "assistant de séduction IA",
  "IA pour draguer",
  "IA drague",
  "IA Tinder",
  "assistant Tinder IA",
  "générateur de phrases de drague IA",
  "générateur de phrases d'accroche IA",
  "générateur de phrases d’accroche IA",
  "générateur de messages Tinder IA",
  "générateur de messages de drague",
  "IA pour répondre à un message",
  "IA pour répondre sur Tinder",
  "quoi répondre à un match Tinder",
  "que répondre à un match Tinder",
  "IA pour flirter",
  "coach séduction IA",
  "coach de drague IA",
  "conseils de drague IA",
  "avoir du rizz",
  "rizz français",
  "rizz en français",
  "générateur de rizz",
  "rizz IA",
  "rizz IA français",
  "application rizz",
  "app rizz",
  "rizz Tinder",
  "rizz sur Tinder",
  "phrase rizz",
  "phrases rizz",
  "réplique rizz",
  "devenir un rizzler",
  "comment avoir du rizz",
  "avoir plus de rizz",
  "disquette de drague",
  "disquettes de drague",
  "meilleures disquettes",
  "disquette Tinder",
  "disquette pour draguer",
  "disquette drôle",
  "disquette romantique",
  "disquette originale",
  "disquette de drague drôle",
  "meilleures disquettes Tinder",
  "quoi répondre à un message",
  "quoi répondre à une fille",
  "quoi répondre à un mec",
  "quoi répondre à un match",
  "quoi répondre sur Tinder",
  "que répondre à son message",
  "que répondre à son crush",
  "réponse à un message Tinder",
  "réponse drôle Tinder",
  "réponse flirt",
  "réponse pour draguer",
  "répondre à un match",
  "répondre à une story",
  "quoi répondre à une story Instagram",
  "réponse à une story",
  "comment répondre à un crush",
  "phrase d'accroche Bumble",
  "phrase d’accroche Bumble",
  "premier message Bumble",
  "phrase d'accroche Hinge",
  "phrase d’accroche Hinge",
  "premier message Hinge",
  "phrase Tinder drôle",
  "phrase Tinder originale",
  "phrase Tinder romantique",
  "phrase Tinder pour faire rire",
  "comment commencer une conversation Tinder",
  "comment parler à un match Tinder",
  "quoi dire à un match Tinder",
  "quoi envoyer après un match Tinder",
  "premier message Tinder drôle",
  "premier message Tinder original",
  "premier message après un match",
  "phrase de drague drôle",
  "phrase d'accroche drôle",
  "phrase d’accroche drôle",
  "message drôle pour Tinder",
  "réponse drôle à un match",
  "phrase de drague romantique",
  "phrase d'accroche romantique",
  "phrase d’accroche romantique",
  "message romantique Tinder",
  "message pour faire craquer une fille",
  "message pour faire craquer un mec",
  "phrase de drague audacieuse",
  "phrase Tinder audacieuse",
  "phrase de drague sexy",
  "message Tinder audacieux",
  "phrase de drague flirt",
  "message flirt",
  "message pour flirter",
  "phrase pour flirter",
  "réponse flirt Tinder",
  "message séduisant",
  "premier message à une fille",
  "premier message à un mec",
  "premier message Tinder original",
  "quoi envoyer après un match",
  "comment commencer une conversation avec son crush",
  // Spanish SEO Keywords
  "asistente de ligue con IA",
  "asistente de citas con IA",
  "asistente de seducción con IA",
  "IA para ligar",
  "IA para citas",
  "IA para coquetear",
  "app de rizz",
  "aplicación de rizz",
  "rizz IA",
  "generador de rizz",
  "rizz en español",
  "rizz español",
  "frases de rizz",
  "frases de ligue",
  "frases para ligar",
  "frases de ligue graciosas",
  "frases para ligar por Tinder",
  "frases para ligar por WhatsApp",
  "frases para ligar por Instagram",
  "frases para romper el hielo",
  "frases para iniciar una conversación",
  "frases de apertura",
  "frases para conquistar",
  "frases coquetas",
  "frases de coqueteo",
  "frases románticas",
  "frases atrevidas",
  "frases graciosas para ligar",
  "frases para conquistar a una chica",
  "frases para conquistar a un chico",
  "generador de frases para ligar",
  "generador de frases de ligue",
  "generador de frases de apertura",
  "generador de mensajes para ligar",
  "generador de mensajes de Tinder",
  "generador de respuestas para ligar",
  "generador de rizz IA",
  "generador de rizz en español",
  "primer mensaje Tinder",
  "primer mensaje después de un match",
  "qué escribir después de un match",
  "qué decirle a mi match",
  "qué responder a un match",
  "qué responder a una chica",
  "qué responder a un chico",
  "qué responder a mi crush",
  "qué escribirle a mi crush",
  "cómo iniciar una conversación en Tinder",
  "cómo ligar en Tinder",
  "cómo ligar por chat",
  "cómo coquetear por chat",
  "consejos para ligar",
  "consejos de seducción",
  "consejos de citas",
  "coach de ligue con IA",
  "coach de seducción con IA",
  "coach de citas con IA",
  "IA para Tinder",
  "Tinder IA",
  "Bumble IA",
  "Hinge IA",
  "asistente de Tinder",
  "respuestas para Tinder",
  "respuestas coquetas",
  "respuestas graciosas",
  "respuestas ingeniosas",
  "respuestas para ligar",
  "cumplidos para ligar",
  "cumplidos para una chica",
  "cumplidos para un chico",
  "cómo tener rizz",
  "tener más rizz",
  "qué es el rizz",
  "Rizzler",
  "app para ligar",
  "app de ligue",
  "app de citas con IA",
  // Japanese SEO Keywords
  "AIナンパアシスタント",
  "AI恋愛アシスタント",
  "AI恋愛相談",
  "AI恋愛コーチ",
  "AIマッチングアシスタント",
  "AIでモテる",
  "AIで恋愛",
  "AIでナンパ",
  "AIで口説く",
  "AIデートアシスタント",
  "AIマッチングアプリ",
  "Rizzアプリ",
  "Rizz AI",
  "Rizzジェネレーター",
  "Rizz生成AI",
  "日本語Rizz",
  "Rizz 日本語",
  "Rizzフレーズ",
  "モテるセリフ",
  "モテる言葉",
  "口説き文句",
  "口説き文句メーカー",
  "口説き文句生成AI",
  "ナンパのセリフ",
  "ナンパフレーズ",
  "ナンパフレーズメーカー",
  "ナンパの言葉",
  "恋愛フレーズ",
  "恋愛セリフ",
  "恋愛メッセージ",
  "恋愛メッセージ生成AI",
  "恋愛LINE",
  "モテるLINE",
  "モテるLINE術",
  "LINEで口説く",
  "LINEでの口説き方",
  "好きな人へのLINE",
  "好きな人に送るメッセージ",
  "気になる人へのメッセージ",
  "初デート メッセージ",
  "マッチングアプリ メッセージ",
  "マッチングアプリ 会話",
  "マッチングアプリ 返信",
  "マッチングアプリ 最初のメッセージ",
  "マッチングアプリ 何を話す",
  "マッチングアプリ 何を送る",
  "マッチ後のメッセージ",
  "マッチ後 何を送る",
  "マッチした後 何を話す",
  "マッチングアプリ 返信例",
  "Tinder メッセージ",
  "Tinder 最初のメッセージ",
  "Tinder マッチ後",
  "Tinder 会話",
  "Tinder 返信",
  "Tinder 口説き方",
  "Bumble メッセージ",
  "Bumble 最初のメッセージ",
  "Hinge メッセージ",
  "恋愛相談 AI",
  "恋愛アドバイス AI",
  "恋愛コーチ AI",
  "モテる方法",
  "モテるための方法",
  "モテる会話",
  "モテる会話術",
  "会話のきっかけ",
  "会話のネタ",
  "会話を続ける方法",
  "会話の始め方",
  "初対面 会話",
  "好きな人との会話",
  "好きな人とLINE",
  "好きな人 返信",
  "何て返せばいい",
  "なんて返信すればいい",
  "LINE 何て返す",
  "好きな人 何て送る",
  "恋愛 返信例",
  "脈あり LINE",
  "褒め言葉",
  "女性を褒める言葉",
  "男性を褒める言葉",
  "面白いメッセージ",
  "面白い返し",
  "気の利いた返し",
  "口説き方",
  "女性の口説き方",
  "男性の口説き方",
  "恋愛テクニック",
  "モテテク",
  "恋愛テクニック AI",
  "Rizzler",
  "Rizzとは",
  "Rizz 日本語 ジェネレーター",
];

/* ─── Global SEO Metadata ─── */
export const metadata: Metadata = {
  title: {
    default: "RIZZ AI - Free AI Dating Assistant & Pickup Lines",
    template: "%s | Rizz AI (www.rizzai.space)",
  },
  description:
    "Generate the best pickup lines with Rizz AI — your free AI-powered flirting tool for Tinder, Bumble, and more. Rizz AI delivers smooth, flirty lines that work!💕",
  keywords: seoKeywords,
  authors: [{ name: "Rizz AI Team", url: "https://www.rizzai.space" }],
  creator: "Rizz AI",
  publisher: "Rizz AI",
  metadataBase: new URL("https://www.rizzai.space"),
  alternates: {
    canonical: "/",
  },
  icons: {
    icon: [
      { url: "/icon.png", sizes: "48x48", type: "image/png" },
      { url: "/icon.png", sizes: "96x96", type: "image/png" },
      { url: "/icon.png", sizes: "192x192", type: "image/png" },
      { url: "/icon.png", sizes: "512x512", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  openGraph: {
    title: "RIZZ AI - Free AI Dating Assistant & Pickup Lines",
    description:
      "Generate the best pickup lines with Rizz AI — your free AI-powered flirting tool for Tinder, Bumble, and more. Rizz AI delivers smooth, flirty lines that work!💕",
    url: "https://www.rizzai.space",
    siteName: "Rizz AI",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/icon.png",
        width: 512,
        height: 512,
        alt: "Rizz AI — #1 Free AI Dating App & AI Wingman",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "RIZZ AI - Free AI Dating Assistant & Pickup Lines",
    description:
      "Generate the best pickup lines with Rizz AI — your free AI-powered flirting tool for Tinder, Bumble, and more. Rizz AI delivers smooth, flirty lines that work!💕",
    creator: "@Vijay_Jadav_7",
    images: ["/icon.png"],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "Dc3uCozuXOMGTsKUWOyzpX2VokIgnkfoSKsfRmg9I1U",
  },
  other: {
    "google-site-verification": "Dc3uCozuXOMGTsKUWOyzpX2VokIgnkfoSKsfRmg9I1U",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "Rizz AI",
    "mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
  },
};

/* ─── Viewport (mobile-first) ─── */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#F6766E",
  viewportFit: "cover",
};

/* ─── Schema.org Structured Data (JSON-LD) ─── */
const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Rizz AI",
  alternateName: [
    "Rizz AI",
    "Rizz App",
    "Dating AI",
    "AI Dating App",
    "Rizz GPT",
    "AI Rizz",
    "Rizz App Online",
    "Rizz App Free",
    "AI Dating Chatbot",
    "rizzai.space",
  ],
  url: "https://www.rizzai.space",
  description:
    "Generate the best pickup lines with Rizz AI — your free AI-powered flirting tool for Tinder, Bumble, and more. Rizz AI delivers smooth, flirty lines that work!💕",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: "https://www.rizzai.space/pickup-line?q={search_term_string}",
    },
    "query-input": "required name=search_term_string",
  },
};

const softwareAppSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "RIZZ AI - Free AI Dating Assistant & Pickup Lines",
  operatingSystem: "Web, iOS, Android",
  applicationCategory: "LifestyleApplication",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.9",
    ratingCount: "14850",
  },
};

const faqPageSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is Rizz AI and how does it work?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Rizz AI (rizzai.space) is a free AI dating app and AI wingman designed to generate charismatic pickup lines, witty conversation replies for Tinder, Hinge, and Bumble, PSL face rating analysis, and couple games.",
      },
    },
    {
      "@type": "Question",
      name: "Is Rizz AI free to use online?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes, Rizz AI is 100% free to use online on both mobile and desktop without requiring any download, credit card, or subscription.",
      },
    },
    {
      "@type": "Question",
      name: "What is Rizz GPT / AI Dating Chatbot?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Rizz GPT is an advanced AI dating chatbot trained to help you craft irresistible dating chat replies, comeback lines, romantic compliments, and conversation starters.",
      },
    },
    {
      "@type": "Question",
      name: "What is RIZZ AI and how does it revolutionize AI dating?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "RIZZ AI is a cutting-edge artificial intelligence platform specifically designed for enhancing dating experiences. By leveraging advanced language models similar to ChatGPT, RIZZ AI revolutionizes AI dating by providing personalized conversation starters, flirting tips, and relationship advice. This innovative tool helps users navigate the complex world of modern dating with confidence and charm.",
      },
    },
    {
      "@type": "Question",
      name: "How does RIZZ AI differ from other AI chatbots in the realm of AI dating?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "RIZZ AI sets itself apart in the AI dating landscape by offering a unique blend of natural language processing and emotional intelligence. Unlike generic chatbots, RIZZ AI is specifically trained on dating scenarios, allowing it to understand nuanced social cues and provide context-appropriate responses. This specialized focus makes RIZZ AI powered by advanced AI an invaluable asset for those looking to improve their dating skills and build meaningful connections.",
      },
    },
    {
      "@type": "Question",
      name: "Can RIZZ AI help improve my dating profile and online presence?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Absolutely! RIZZ AI is equipped with advanced algorithms that analyze successful dating profiles and online interactions. By utilizing RIZZ AI, you can receive tailored suggestions to optimize your dating profile, select the most appealing photos, and craft engaging bios. The AI dating assistant can also provide real-time feedback on your online conversations, helping you maintain interesting and flirtatious exchanges that are more likely to lead to successful matches.",
      },
    },
    {
      "@type": "Question",
      name: "How does RIZZ AI ensure privacy and security in the context of AI dating?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Privacy and security are paramount in RIZZ AI's design. The platform employs end-to-end encryption for all communications and does not store personal conversation data permanently. RIZZ AI operates on a privacy-first principle, ensuring that your dating conversations and personal information remain confidential. The AI dating assistant processes information locally when possible and adheres to strict data protection protocols, giving users peace of mind while improving their dating skills.",
      },
    },
  ],
};

const orgSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Rizz AI",
  url: "https://www.rizzai.space",
  logo: "https://www.rizzai.space/icon.png",
  sameAs: ["https://x.com/Vijay_Jadav_7"],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={lilitaOne.variable} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <LanguageProvider>
          <ThemeProvider>
            <ErrorBoundary>
              <SoundListener />
              {children}
            </ErrorBoundary>
          </ThemeProvider>
        </LanguageProvider>

        {/* Structured Data (JSON-LD) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareAppSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPageSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }}
        />
      </body>
    </html>
  );
}
